<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     local_forum_ai
 * @category    string
 * @copyright   2025 Datacurso
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['actions'] = 'Actions';
$string['ai_response'] = 'AI Response';
$string['ai_response_approved'] = 'Approved AI Response';
$string['ai_response_proposed'] = 'Proposed AI Response';
$string['ai_response_rejected'] = 'Rejected AI Response';
$string['aiproposed'] = 'Proposed AI Response';
$string['alreadysubmitted'] = 'This request has already been approved, rejected, or does not exist.';
$string['approve'] = 'Approve';
$string['backtodiscussion'] = 'Back to discussion';
$string['cancel'] = 'Cancel';
$string['col_message'] = 'Message';
$string['course'] = 'Course';
$string['coursename'] = 'Course';
$string['created'] = 'Created';
$string['datacurso_custom'] = 'Datacurso Forum AI';
$string['default_reply_message'] = 'Respond with an empathetic and motivating tone';
$string['discussion'] = 'Discussion';
$string['discussion_label'] = 'Discussion: {$a}';
$string['discussioninfo'] = 'Discussion Information';
$string['discussionmsg'] = 'AI generated message';
$string['discussionname'] = 'Subject';
$string['enabled'] = 'Enable AI';
$string['forum'] = 'Forum';
$string['forumname'] = 'Forum';
$string['historyresponses'] = 'AI Forum Response History';
$string['level'] = 'Level: {$a}';
$string['modal_title'] = 'Discussion History Details';
$string['modal_title_pending'] = 'Discussion Details';
$string['no'] = 'No';
$string['no_posts'] = 'No posts found in this discussion.';
$string['nohistory'] = 'No approved or rejected AI responses found.';
$string['nopermission'] = 'You do not have permission to approve or reject AI responses.';
$string['noresponses'] = 'No pending AI responses.';
$string['originalmessage'] = 'Original message';
$string['pendingresponses'] = 'Pending AI Forum Responses';
$string['pluginname'] = 'Forum AI';
$string['preview'] = 'AI Message';
$string['privacy:metadata:local_forum_ai_pending'] = 'Data stored by the Forum AI plugin.';
$string['privacy:metadata:local_forum_ai_pending:approval_token'] = 'Approval token linked to the post.';
$string['privacy:metadata:local_forum_ai_pending:approved_at'] = 'Date when the response was approved.';
$string['privacy:metadata:local_forum_ai_pending:creator_userid'] = 'User ID who created the post.';
$string['privacy:metadata:local_forum_ai_pending:discussionid'] = 'Related discussion ID.';
$string['privacy:metadata:local_forum_ai_pending:forumid'] = 'Forum ID where the response was generated.';
$string['privacy:metadata:local_forum_ai_pending:message'] = 'Message generated by AI.';
$string['privacy:metadata:local_forum_ai_pending:status'] = 'Publication status (approved, pending, or rejected).';
$string['privacy:metadata:local_forum_ai_pending:subject'] = 'Message subject.';
$string['privacy:metadata:local_forum_ai_pending:timecreated'] = 'Record creation date.';
$string['privacy:metadata:local_forum_ai_pending:timemodified'] = 'Record modification date.';
$string['reject'] = 'Reject';
$string['reply_message'] = 'Give instructions to the AI';
$string['replylevel'] = 'Reply level {$a}';
$string['require_approval'] = 'Review AI response';
$string['reviewtitle'] = 'Review AI response';
$string['save'] = 'Save';
$string['saveapprove'] = 'Save and approve';
$string['settings'] = 'Settings for: ';
$string['status'] = 'Status';
$string['statusapproved'] = 'Approved';
$string['statuspending'] = 'Pending';
$string['statusrejected'] = 'Rejected';
$string['username'] = 'Creator';
$string['viewdetails'] = 'View details';
$string['yes'] = 'Yes';
