<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     local_forum_ai
 * @category    string
 * @copyright   2025 Datacurso
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['actions'] = 'Actions';
$string['ai_response'] = 'AI Response';
$string['ai_response_approved'] = 'AI Response Approved';
$string['ai_response_proposed'] = 'AI Response Proposed';
$string['ai_response_rejected'] = 'AI Response Rejected';
$string['aiproposed'] = 'AI Proposed Response';
$string['alreadysubmitted'] = 'This request has already been approved, rejected or does not exist.';
$string['approve'] = 'Approve';
$string['backtodiscussion'] = 'Back to discussion';
$string['cancel'] = 'Cancel';
$string['col_message'] = 'Message';
$string['course'] = 'Course';
$string['coursename'] = 'Course';
$string['created'] = 'Created';
$string['datacurso_custom'] = 'Datacurso Forum AI';
$string['default_reply_message'] = 'Reply with an empathetic and motivational tone';
$string['discussion'] = 'Discussion';
$string['discussion_label'] = 'Discussion: {$a}';
$string['discussioninfo'] = 'Discussion information';
$string['discussionmsg'] = 'Message generated by AI';
$string['discussionname'] = 'Subject';
$string['enabled'] = 'Enable AI';
$string['error_airequest'] = 'Error communicating with the AI service: {$a}';
$string['forum'] = 'Forum';
$string['forumname'] = 'Forum';
$string['historyresponses'] = 'Forum AI Response History';
$string['level'] = 'Level: {$a}';
$string['messageprovider:ai_approval_request'] = 'AI approval request';
$string['modal_title'] = 'Discussion history details';
$string['modal_title_pending'] = 'Discussion details';
$string['no'] = 'No';
$string['no_posts'] = 'No posts found in this discussion.';
$string['nohistory'] = 'No approved or rejected AI response history.';
$string['nopermission'] = 'You do not have permission to approve/reject AI responses.';
$string['noresponses'] = 'There are no responses pending approval.';
$string['notification_approve_link'] = 'Approve directly: {$a->url}';
$string['notification_course_label'] = 'Course';
$string['notification_greeting'] = 'Hello {$a->firstname},';
$string['notification_intro'] = 'An automated response has been generated for the discussion "{$a->discussion}" in the forum "{$a->forum}" of the course "{$a->course}".';
$string['notification_preview'] = 'Preview:';
$string['notification_reject_link'] = 'Reject: {$a->url}';
$string['notification_review_button'] = 'Review response';
$string['notification_review_link'] = 'Review and approve the response at: {$a->url}';
$string['notification_smallmessage'] = 'New pending AI response in "{$a->discussion}"';
$string['notification_subject'] = 'Approval required: AI Response';
$string['originalmessage'] = 'Original message';
$string['pendingresponses'] = 'Pending Forum AI Responses';
$string['pluginname'] = 'Forum AI';
$string['preview'] = 'AI Message';
$string['privacy:metadata:local_forum_ai_config'] = 'Stores AI settings per forum.';
$string['privacy:metadata:local_forum_ai_config:enabled'] = 'Indicates whether AI is enabled for this forum.';
$string['privacy:metadata:local_forum_ai_config:forumid'] = 'The forum ID this configuration belongs to.';
$string['privacy:metadata:local_forum_ai_config:reply_message'] = 'Template for AI-generated reply.';
$string['privacy:metadata:local_forum_ai_config:require_approval'] = 'Indicates whether AI replies require approval before publishing.';
$string['privacy:metadata:local_forum_ai_config:timecreated'] = 'Configuration creation date.';
$string['privacy:metadata:local_forum_ai_config:timemodified'] = 'Date of last modification of the configuration.';
$string['privacy:metadata:local_forum_ai_pending'] = 'Data stored by the Forum AI plugin.';
$string['privacy:metadata:local_forum_ai_pending:approval_token'] = 'Approval token linked to the post.';
$string['privacy:metadata:local_forum_ai_pending:approved_at'] = 'Date the response was approved.';
$string['privacy:metadata:local_forum_ai_pending:creator_userid'] = 'ID of the user who created the post.';
$string['privacy:metadata:local_forum_ai_pending:discussionid'] = 'ID of the related discussion.';
$string['privacy:metadata:local_forum_ai_pending:forumid'] = 'ID of the forum where the response was generated.';
$string['privacy:metadata:local_forum_ai_pending:message'] = 'Message generated by artificial intelligence.';
$string['privacy:metadata:local_forum_ai_pending:status'] = 'Status of the post (approved, pending or rejected).';
$string['privacy:metadata:local_forum_ai_pending:subject'] = 'Subject or topic of the message.';
$string['privacy:metadata:local_forum_ai_pending:timecreated'] = 'Date the record was created.';
$string['privacy:metadata:local_forum_ai_pending:timemodified'] = 'Date the record was updated.';
$string['reject'] = 'Reject';
$string['reply_message'] = 'Give instructions to the AI';
$string['replylevel'] = 'Reply level {$a}';
$string['require_approval'] = 'Require AI review';
$string['reviewtitle'] = 'Review AI Response';
$string['save'] = 'Save';
$string['saveapprove'] = 'Save and Approve';
$string['settings'] = 'Settings for: ';
$string['status'] = 'Status';
$string['statusapproved'] = 'Approved';
$string['statuspending'] = 'Pending';
$string['statusrejected'] = 'Rejected';
$string['username'] = 'Creator';
$string['viewdetails'] = 'Details';
$string['yes'] = 'Yes';
