<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     local_forum_ai
 * @category    string
 * @copyright   2025 Piero Llanos <piero@datacurso.com>
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['actions'] = 'Actions';
$string['ai_response'] = 'AI Response';
$string['ai_response_approved'] = 'AI Response Approved';
$string['ai_response_proposed'] = 'Proposed AI Response';
$string['ai_response_rejected'] = 'AI Response Rejected';
$string['aiproposed'] = 'Proposed AI Response';
$string['alreadysubmitted'] = 'This request has already been approved, rejected, or does not exist.';
$string['approve'] = 'Approve';
$string['backtodiscussion'] = 'Return to discussion';
$string['cancel'] = 'Cancel';
$string['col_message'] = 'Message';
$string['course'] = 'Course';
$string['coursename'] = 'Course';
$string['created'] = 'Created';
$string['datacurso_custom'] = 'Datacurso Forum AI';
$string['default_reply_message'] = 'Respond with an empathetic and motivating tone';
$string['discussion'] = 'Discussion';
$string['discussion_label'] = 'Discussion: {$a}';
$string['discussioninfo'] = 'Discussion information';
$string['discussionmsg'] = 'Message generated by AI';
$string['discussionname'] = 'Subject';
$string['enabled'] = 'Enable AI';
$string['forum'] = 'Forum';
$string['forumname'] = 'Forum';
$string['historyresponses'] = 'Forum AI Response History';
$string['level'] = 'Level: {$a}';
$string['modal_title'] = 'Discussion history details';
$string['modal_title_pending'] = 'Discussion details';
$string['no'] = 'No';
$string['no_posts'] = 'No posts found in this discussion.';
$string['nohistory'] = 'No history of approved or rejected AI responses.';
$string['nopermission'] = 'You do not have permission to approve/reject AI responses.';
$string['noresponses'] = 'There are no responses pending approval.';
$string['originalmessage'] = 'Original Message';
$string['pendingresponses'] = 'Pending Forum AI Responses';
$string['pluginname'] = 'Forum AI';
$string['preview'] = 'AI Message';
$string['reject'] = 'Reject';
$string['reply_message'] = 'Give directions to the AI';
$string['replylevel'] = 'Reply level {$a}';
$string['require_approval'] = 'Check AI response';
$string['reviewtitle'] = 'Review AI Response';
$string['save'] = 'Save';
$string['saveapprove'] = 'Save and Approve';
$string['settings'] = 'Settings for: ';
$string['status'] = 'Status';
$string['statusapproved'] = 'Approved';
$string['statuspending'] = 'Pending';
$string['statusrejected'] = 'Rejected';
$string['username'] = 'Creator';
$string['viewdetails'] = 'Details';
$string['yes'] = 'Yes';
